"""empty message

Revision ID: 01c3bcedd565
Revises: 3a96cff864e0
Create Date: 2021-08-05 15:08:55.050484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c3bcedd565'
down_revision = '3a96cff864e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=True),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('msrp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('frame_material', sa.String(length=150), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('max_speed', sa.String(length=100), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('stock_weight', sa.String(length=50), nullable=True),
    sa.Column('series', sa.String(length=150), nullable=True),
    sa.Column('user_token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_table('bike')
    # ### end Alembic commands ###
