"""empty message

Revision ID: 18ee905a7e00
Revises: 01c3bcedd565
Create Date: 2021-08-05 17:03:48.453830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ee905a7e00'
down_revision = '01c3bcedd565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('size', sa.String(length=25), nullable=True))
    op.add_column('bike', sa.Column('speeds', sa.String(length=10), nullable=True))
    op.drop_column('bike', 'dimensions')
    op.drop_column('bike', 'max_speed')
    op.drop_column('bike', 'series')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('series', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('bike', sa.Column('max_speed', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('bike', sa.Column('dimensions', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('bike', 'speeds')
    op.drop_column('bike', 'size')
    # ### end Alembic commands ###
