"""empty message

Revision ID: e1df066d35ad
Revises: 18ee905a7e00
Create Date: 2021-08-18 21:00:14.997244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1df066d35ad'
down_revision = '18ee905a7e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('model', sa.String(length=150), nullable=True))
    op.add_column('bike', sa.Column('frameMaterial', sa.String(length=150), nullable=True))
    op.drop_column('bike', 'speeds')
    op.drop_column('bike', 'model_name')
    op.drop_column('bike', 'stock_weight')
    op.drop_column('bike', 'msrp')
    op.drop_column('bike', 'frame_material')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('frame_material', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('bike', sa.Column('msrp', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('bike', sa.Column('stock_weight', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('bike', sa.Column('model_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('bike', sa.Column('speeds', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('bike', 'frameMaterial')
    op.drop_column('bike', 'model')
    # ### end Alembic commands ###
